print("hello");
x=5;
y="viji";
q=str(5);
w=float(4);
r=int(8.0);
print(q,w,r)
print(x,y);
o=(type(5));
p=(type('viji'));
print(o,p);
z=["apple","banana","cherry"];
a,b,c=z;
print(a);
fruit=("berry","kiwi","apple");
(blue,white,red)=fruit;
print(blue);
fruits=("apple","banana","kiwi","cherry","greenapple")
(red,yellow,*orange)=fruits
print(fruits)
print(orange);
g=h=j="Sample"
print(h);
m="viji"
n="ishwarya"
print(m+n);
print(m,n)
f=4;
u=6;
print(f,u);
print(f+u);
