import re
s="Hi, this is viJi /// 2025"
check=re.search(r"viji",s,flags=re.IGNORECASE)
print("start:",check.start())
print("End:",check.end())
print("span:",check.span())
# reg=re.search(r"\D{2}v",s)
# print(reg)
reg=re.search(r"\D{2} v",s)
print(reg)
print(reg.group())
# print(re.findall(r"i",s))
# x=re.compile(s)
# print(x)
# print(re.split(r"t",s))
# print(re.sub(r"viji","ish",s))
# print(re.escape(s))
# c=re.compile(r"[j-u]",s)
# print(c.findall(s))
# print(re.findall(r"[j-u]",s,flags=re.IGNORECASE))
# t=re.compile("\d")
# print(t.findall(s))
# t=re.compile("\d+")
# print(t.findall(s))
# y=re.compile("\w")
# print(y.findall(s))
# z=re.compile("\w+")
# print(z.findall(s))
# x=re.compile("\W")
# print(x.findall(s))
# q=re.compile("ab")
# print(q.findall("abaabbb"))
# w=re.compile("ab*")
# print(w.findall("abaabbb"))
# t=re.split("\w+","Words are splited 2025")
# print(t)
# t=re.split("\W+","Words are splited 2025")
# print(t)
# t=re.split("\w","Words are splited 2025")
# print(t)
# t=re.split("\W","Words are splited 2025")
# print(t)
# o=re.search("^Hi",s)
# print(o)
# o=re.search("5$",s)
# print(o)
# i=re.search("v.j",s,flags=re.IGNORECASE)
# print(i)
# l=re.search("iv?J",s)
# print(l)
# k=re.search("vi+j",s)
# print(k)
# k=re.search("vi+j",s,flags=re.IGNORECASE)
# print(k)
# g=re.search("\AHi",s)
# print(g)
# f="This year was good:2025"
# b=re.search("\d[[0-9]",f)
# print(b)